### ISSUE TITLE
type(MyCustomError) === 'Object' ?

### ISSUE THREAD

**Issue by alexshuhin** [sanctuary-js/sanctuary-type-identifiers#14]
I get an error while using [js-yaml](https://github.com/nodeca/js-yaml) lib with sanctury's `encaseEither` function:
```javascript
const { safeLoad } = require('js-yaml');
const parseYaml = encaseEither(I, safeLoad);
parseYaml('Some invalid yaml');
```
Here what i get:
```
TypeError: Invalid value

encaseEither :: (Error -> l) -> (a -> r) -> a -> Either l r
                 ^^^^^
                   1

1)  YAMLException: end of the stream or a document separator is expected at line 2, column 8:
      redis:
           ^ :: Object, StrMap ???

The value at position 1 is not a member of ‘Error’.
```
`YAMLException` defined as MDN recommends in its examples: https://github.com/nodeca/js-yaml/blob/master/lib/js-yaml/exception.js and MDN examples https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Error#Custom_Error_Types

[type](https://github.com/sanctuary-js/sanctuary-type-identifiers/blob/v2.0.1/index.js#L154-L161) determines `YAMLException` as `Object`, and thats looks wierd

My runtime is `node 8.1.3`

**Comment by davidchambers** [comment]
We rely on `Object#toString` to determine whether a value is an Error. The error thrown by `safeLoad` identifies itself as `[object Object]` rather than `[object Error]`, as shown below:

```javascript
const {safeLoad} = require('js-yaml');
const S = require('sanctuary').create({checkTypes: false, env: []});

const parseYaml = S.encaseEither(S.I, safeLoad);

Object.prototype.toString.call(parseYaml(':').value);
// => '[object Object]'

Object.prototype.toString.call(new Error('XXX'));
// => '[object Error]'
```

I believe `safeLoad` should be updated to throw something which responds "correctly" to `Object#toString`.

**Comment by Avaq** [comment]
> I believe `safeLoad` should be updated to throw something which responds "correctly" to `Object#toString`.

I think the only way to achieve this is to override `Object#toString`'s native behavior for these values, which has been made possible only recently through the addition of [`Symbol.toStringTag`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toStringTag). Using this Symbol has not yet been adopted as a recommended way to tag your Error values, and probably never will be. I would also not want Sanctuary to push users towards using Symbols. If I haven't missed anything in my research about this issue, I think I would vote for `sanctuary-def` to be updated to something like this:

```diff
-var Error_ = NullaryTypeWithUrl('Error', Any, typeEq('Error'));
+var Error_ = NullaryTypeWithUrl('Error', Any, typeEqOrInherits('Error'));
```

...where `typeEqOrInherits` walks the prototype chain of the value to see if it finds that 'Error' has one of its "parent" values.

**Comment by davidchambers** [comment]
Thanks for the information, Aldwin. How might the implementation of `typeEqOrInherits` look?

**Comment by Avaq** [comment]
Bah. I think `typeEqOrInherits` does not work, because none of the objects in the prototype chain (including the one which has `o.constructor === Error`) have the property that `Object.prototype.toString.call(o) === '[object Error]'`. :\

**Comment by Avaq** [comment]
An alternative would be to rely on `o.constructor === Error`; essentially `instanceof`, but then we are back to `vm.runInNewContext('new Error')` and the likes not being `$.Error`s.

**Comment by davidchambers** [comment]
I'm unwilling to consider `instanceof`. Problems with `instanceof` led to the creation of this spec/package. ;)

In my experience simply using `new Error('...')` is a good idea. One is of course free to define properties on the resulting Error object:

```javascript
const err = new Error('...');
err.isYamlException = true;
```
