### ISSUE TITLE
A default export of identifierOf will increase compatibility with the existing ecosystem

### ISSUE THREAD

**Issue by jceb** [sanctuary-js/sanctuary-type-identifiers#63]
https://github.com/sanctuary-js/sanctuary-type-identifiers/blob/be7c6e6bc6450089f1314fba4f44488637beb9cb/index.js#L56

**Comment by davidchambers** [comment]
I don't see how this is so. If `sanctuary-foo@1.0.0` depends on the CommonJS version of this library it will always depend on the CommonJS version and will continue to work. If `sanctuary-foo@2.0.0` depends on the (forthcoming) ESM version of this library it will use the appropriate `import` declarations. I don't see a reason to make `sanctuary-foo@1.0.0` compatible with the ESM version of this library as it will never depend on the ESM version. Am I missing something? :)

**Comment by jceb** [comment]
Well, yes, you're right :+1:
